services:
  pgsql:
    image: 'postgres:17'
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: 'secret'
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - 'sail-backup:/var/lib/postgresql/data'
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
        - 'sail-redis:/data'
    networks:
        - sail
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        retries: 3
        timeout: 5s
    command: redis-server --appendonly yes --replica-read-only no
networks:
  sail:
    driver: bridge
volumes:
  sail-backup:
    driver: local
  sail-redis:
    driver: local

